import { Router } from "express";
import fs from 'fs';

const router = Router();

router.get('/', function (req, res) {
  var result = "";
  result += "<!DOCTYPE html>\n";
  result += "<html lang=\"en\">\n";
  result += "\n";
  result += "<head>\n";
  result += "  <meta charset=\"UTF-8\">\n";
  result += "  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n";
  result += "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
  result += "  <title>Sistema de Información Académica</title>\n";
  result += "  <style>\n";
  result += "    a {\n";
  result += "      text-decoration: none;\n";
  result += "      cursor: pointer;\n";
  result += "      color: black;\n";
  result += "    }\n";
  result += "  </style>\n";
  result += "</head>\n";
  result += "\n";
  result += "<body><br><br>\n";
  result += "  <label style=\"text-align: center;\">\n";
  result += "    <h1>Sistema de Información Académica</h1>\n";
  result += "  </label>\n";
  result += "  <br><br><br>\n";
  result += "  <label style=\"text-align: center;\">\n";
  result += "    <a href=\"https://frontrequisitos.herokuapp.com/\">\n";
  result += "      <h3>Grupo 1 - Ciclo de la Matrícula</h3>\n";
  result += "    </a>\n";
  result += "  </label>\n";
  result += "  <label style=\"text-align: center;\">\n";
  result += "    <a href=\"https://requisitos.herokuapp.com/\">\n";
  result += "      <h3>Grupo 2 - Ciclo de vida de las asignaturas</h3>\n";
  result += "    </a>\n";
  result += "  </label>\n";
  result += "  <label style=\"text-align: center;\">\n";
  result += "    <a href=\"https://planes-de-estudio.herokuapp.com/\">\n";
  result += "      <h3>Grupo 3 - Ciclo de vida de los planes de estudio</h3>\n";
  result += "    </a>\n";
  result += "  </label>\n";
  result += "  <label style=\"text-align: center;\">\n";
  result += "    <a href=\"https://sia-perfil-sociodemografico.herokuapp.com/\">\n";
  result += "      <h3>Grupo 6 - Perfil sociodemografico</h3>\n";
  result += "    </a>\n";
  result += "  </label>\n";
  result += "  <label style=\"text-align: center;\">\n";
  result += "    <a href=\"https://programacion-academica.vercel.app/\">\n";
  result += "      <h3>Grupo 7 - Ciclo de Vida Programación Académica</h3>\n";
  result += "    </a>\n";
  result += "  </label>\n";
  result += "  <label style=\"text-align: center;\">\n";
  result += "    <a href=\"https://ciclo-vida-docencia.herokuapp.com/\">\n";
  result += "      <h3>Grupo 8 - Ciclo de Vida De La Docencia</h3>\n";
  result += "    </a>\n";
  result += "  </label>\n";
  result += "</body>\n";
  result += "\n";
  result += "</html>\n";
  res.send(result);
});

export default router;